export interface SearchResult {
  id: string;
  title: string;
  author?: string;
  duration: string;
  views?: string;
  thumbnailUrl?: string;
  img?: string;
  source?: string;
  type?: string;
  albumId?: string;
  albumName?: string;
  uploaded?: string;
  href?: string;
  videoCount?: number;
  channelDescription?: string;
  verified?: boolean;
}

export interface SearchResponse {
  items: SearchResult[];
  nextpage?: string | null;
}

export interface RawPipedItem {
  url?: string;
  type?: string;
  title?: string;
  thumbnail?: string;
  uploaderName?: string;
  uploaderUrl?: string;
  uploaderAvatar?: string;
  uploadedDate?: string;
  shortDescription?: string;
  duration?: number;
  views?: number;
  uploaded?: number | string;
  uploaderVerified?: boolean;
  isShort?: boolean;
  [key: string]: unknown;
}

export interface InvidiousThumbnail {
  quality: string;
  url: string;
  width: number;
  height: number;
}

export interface InvidiousVideoItem {
  type: "video";
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  videoThumbnails: InvidiousThumbnail[];
  description: string;
  descriptionHtml: string;
  viewCount: number;
  published: number;
  publishedText: string;
  lengthSeconds: number;
  liveNow: boolean;
  paid: boolean;
  premium: boolean;
}

export interface InvidiousPlaylistItem {
  type: "playlist";
  title: string;
  playlistId: string;
  playlistThumbnail: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  videoCount: number;
  videos: Array<{
    title: string;
    videoId: string;
    lengthSeconds: number;
    videoThumbnails: InvidiousThumbnail[];
  }>;
}

export interface InvidiousChannelItem {
  type: "channel";
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: InvidiousThumbnail[];
  autoGenerated: boolean;
  subCount: number;
  videoCount: number;
  description: string;
  descriptionHtml: string;
}

export type InvidiousSearchItem = InvidiousVideoItem | InvidiousPlaylistItem | InvidiousChannelItem;

// SoundCloud
export interface SoundCloudTrackResponse {
  collection: SoundCloudTrack[];
}
export interface SoundCloudTrack {
  kind: string;
  id: number;
  title: string;
  duration: number;
  playback_count: number;
  created_at: string;
  permalink_url: string;
  artwork_url?: string;
  user: {
    username: string;
    avatar_url: string;
  };
}
export interface SoundCloudCollectionItem {
  permalink_url?: string;
  url?: string;
  title: string;
  name?: string;
  user?: { username: string; avatar_url: string };
  artist?: string;
  author?: string;
  track_count?: number;
  tracks?: unknown[];
  artwork_url?: string;
  artwork?: string;
  avatar_url?: string;
}
export interface SoundCloudCollectionResponse {
  collection?: SoundCloudCollectionItem[];
  results?: SoundCloudCollectionItem[];
}

// JioSaavn
export interface JioSaavnImage {
  quality: string;
  url: string;
}
export interface JioSaavnSong {
  id: string;
  song?: string;
  name?: string;
  singers?: string;
  primaryArtists?: string;
  duration?: string;
  image?: JioSaavnImage[];
  album?: { id: string; name: string; url: string };
}
export interface JioSaavnAlbum {
  id: string;
  title: string;
  artist?: string;
  year?: string;
  image?: JioSaavnImage[];
}
export interface JioSaavnArtist {
  id: string;
  title: string;
  description?: string;
  image?: JioSaavnImage[];
}
export interface JioSaavnResultSet {
  results?: JioSaavnSong[] | JioSaavnAlbum[] | JioSaavnArtist[] | unknown[];
}
export interface JioSaavnSearchData {
  topQuery?: { results?: unknown[] };
  songs?: JioSaavnResultSet;
  albums?: JioSaavnResultSet;
  artists?: JioSaavnResultSet;
}
export interface JioSaavnSearchResponse {
  success: boolean;
  data?: JioSaavnSearchData;
}