import { NextRequest, NextResponse } from "next/server";

const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36";

const INVIDIOUS_BASE = "https://yt.omada.cafe";

function isYouTubeChannelId(id: string): boolean {
  return id.startsWith("UC") || id.startsWith("U") || id.length === 24;
}

function safeString(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function safeNumber(value: unknown): number {
  if (typeof value === "number") return value;
  if (typeof value === "string") {
    const n = parseInt(value, 10);
    return Number.isNaN(n) ? 0 : n;
  }
  return 0;
}

async function fetchJson(url: string): Promise<unknown> {
  const res = await fetch(url, {
    headers: { "User-Agent": USER_AGENT, accept: "application/json" },
    cache: "no-store",
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`HTTP ${res.status} ${text}`);
  }

  return res.json() as Promise<unknown>;
}

type ArtistPayload = {
  artist: {
    id: string;
    name: string;
    image?: string;
    banner?: string;
    subscribers?: number;
    verified?: boolean;
    description?: string;
  };
  songs: Array<{
    id: string;
    title: string;
    thumbnail?: string;
    views?: number;
    duration?: number;
  }>;
  albums: Array<{
    id: string;
    title: string;
    thumbnail?: string;
    year?: string;
    videoCount?: number;
  }>;
  playlists: Array<{
    id: string;
    title: string;
    thumbnail?: string;
    videoCount?: number;
  }>;
};

async function fetchInvidiousChannel(channelId: string): Promise<unknown> {
  return fetchJson(
    `${INVIDIOUS_BASE}/api/v1/channels/${encodeURIComponent(channelId)}`
  );
}

async function fetchInvidiousChannelVideos(
  channelId: string
): Promise<unknown> {
  return fetchJson(
    `${INVIDIOUS_BASE}/api/v1/channels/${encodeURIComponent(channelId)}/videos`
  );
}

async function fetchInvidiousChannelPlaylists(
  channelId: string
): Promise<unknown> {
  return fetchJson(
    `${INVIDIOUS_BASE}/api/v1/channels/${encodeURIComponent(
      channelId
    )}/playlists`
  );
}

function absolutizeUrl(url: string): string {
  if (!url) return url;
  if (url.startsWith("https://") || url.startsWith("http://")) return url;
  if (url.startsWith("//")) return `https:${url}`;
  if (url.startsWith("/")) return `${INVIDIOUS_BASE}${url}`;
  return url;
}

function pickBestImageUrl(arr: unknown, urlKey: string = "url"): string {
  if (!Array.isArray(arr) || arr.length === 0) return "";
  const sorted = [...arr]
    .map((x) => x as Record<string, unknown>)
    .sort((a, b) => safeNumber(b.width) - safeNumber(a.width));
  const url = safeString(sorted[0]?.[urlKey]);
  return absolutizeUrl(url);
}

function isAutoGeneratedAlbumPlaylistId(playlistId: string): boolean {
  return playlistId.startsWith("OLAK5uy") || playlistId.startsWith("MPREb_");
}

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const id = searchParams.get("id");
  if (!id) return NextResponse.json({ error: "Missing id" }, { status: 400 });

  if (!isYouTubeChannelId(id)) {
    return NextResponse.json(
      {
        artist: { id, name: id },
        songs: [],
        albums: [],
        playlists: [],
      } satisfies ArtistPayload,
      { status: 200 }
    );
  }

  try {
    const invidiousChannel = (await fetchInvidiousChannel(id)) as Record<
      string,
      unknown
    >;

    const nameRaw =
      safeString(invidiousChannel.author) || safeString(invidiousChannel.name);
    const name = nameRaw.replace(/\s*-\s*Topic$/i, "") || "Artist";

    const artist: ArtistPayload["artist"] = {
      id,
      name,
      image: pickBestImageUrl(invidiousChannel.authorThumbnails),
      banner: pickBestImageUrl(invidiousChannel.authorBanners),
      subscribers: safeNumber(invidiousChannel.subCount),
      verified: Boolean(invidiousChannel.verified),
      description: safeString(invidiousChannel.description),
    };

    const latestVideos = Array.isArray(invidiousChannel.latestVideos)
      ? (invidiousChannel.latestVideos as Array<Record<string, unknown>>)
      : [];

    const videosFallback =
      latestVideos.length === 0
        ? ((await fetchInvidiousChannelVideos(id).catch(
            () => []
          )) as unknown as Array<Record<string, unknown>>)
        : [];

    const videosToUse = latestVideos.length > 0 ? latestVideos : videosFallback;

    const songs = videosToUse.map((v) => {
      const thumbnails = v.videoThumbnails;
      return {
        id: safeString(v.videoId) || safeString(v.id),
        title: safeString(v.title) || "Unknown",
        thumbnail: pickBestImageUrl(thumbnails),
        views: safeNumber(v.viewCount),
        duration: safeNumber(v.lengthSeconds),
      };
    });

    const playlistsRaw = (await fetchInvidiousChannelPlaylists(id).catch(
      () => []
    )) as unknown;

    const playlistsList = Array.isArray(playlistsRaw)
      ? (playlistsRaw as Array<Record<string, unknown>>)
      : [];

    const albums: ArtistPayload["albums"] = [];
    const playlists: ArtistPayload["playlists"] = [];

    for (const p of playlistsList) {
      const playlistId = safeString(p.playlistId) || safeString(p.id);
      const payload = {
        id: playlistId,
        title: safeString(p.title) || "Unknown",
        thumbnail: absolutizeUrl(safeString(p.playlistThumbnail)),
        videoCount: safeNumber(p.videoCount),
      };

      if (isAutoGeneratedAlbumPlaylistId(playlistId)) albums.push(payload);
      else playlists.push(payload);
    }

    return NextResponse.json(
      {
        artist,
        songs,
        albums,
        playlists,
      } satisfies ArtistPayload,
      { status: 200 }
    );
  } catch {
    return NextResponse.json(
      { error: "Failed to load artist" },
      { status: 500 }
    );
  }
}
