name = "api"
main = "src/index.ts"
compatibility_date = "2026-06-30"

[vars]
WORKER_ENV = "preview"
CONFIG_URL = "https://instances.streamify.workers.dev/config"
ALLOWED_ORIGINS = "http://localhost:3000,http://127.0.0.1:3000,https://streamifypreview.vercel.app,https://streamify-player.netlify.app,https://streamify-player.vercel.app"