name = "streamifyapi"
main = "src/index.ts"
compatibility_date = "2026-06-30"

[vars]
WORKER_ENV = "preview"
CONFIG_URL = "https://streamifyinstances.erfannodes.workers.dev/config"
ALLOWED_ORIGINS = "https://streamifypreview.vercel.app"
