import express from "express";
import cors from "cors";
import { fetch as undiciFetch, ProxyAgent, type RequestInit } from "undici";

const app = express();
const PORT = process.env.PORT || 3001;
app.use(cors({ origin: "http://localhost:3000" }));

// ---------- TYPES ----------

// For raw Piped items (YouTube / YouTube Music)
interface RawPipedItem {
  url?: string;
  type?: string;
  title?: string;
  thumbnail?: string;
  uploaderName?: string;
  uploaderUrl?: string;
  uploaderAvatar?: string;
  uploadedDate?: string;
  shortDescription?: string;
  duration?: number;
  views?: number;
  uploaded?: number | string;
  uploaderVerified?: boolean;
  isShort?: boolean;
  [key: string]: unknown;
}

// Invidious API v1 search result item (video)
interface InvidiousVideoItem {
  type: "video";
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  videoThumbnails: Array<{
    quality: string;
    url: string;
    width: number;
    height: number;
  }>;
  description: string;
  descriptionHtml: string;
  viewCount: number;
  published: number;
  publishedText: string;
  lengthSeconds: number;
  liveNow: boolean;
  paid: boolean;
  premium: boolean;
}

// Invidious playlist item
interface InvidiousPlaylistItem {
  type: "playlist";
  title: string;
  playlistId: string;
  playlistThumbnail: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  videoCount: number;
  videos: Array<{
    title: string;
    videoId: string;
    lengthSeconds: number;
    videoThumbnails: InvidiousVideoItem["videoThumbnails"];
  }>;
}

// Invidious channel item
interface InvidiousChannelItem {
  type: "channel";
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: Array<{
    url: string;
    width: number;
    height: number;
  }>;
  autoGenerated: boolean;
  subCount: number;
  videoCount: number;
  description: string;
  descriptionHtml: string;
}

type InvidiousSearchItem =
  | InvidiousVideoItem
  | InvidiousPlaylistItem
  | InvidiousChannelItem;

// SoundCloud API response types
interface SoundCloudTrackResponse {
  collection: SoundCloudTrack[];
}
interface SoundCloudTrack {
  kind: string;
  id: number;
  title: string;
  duration: number;
  playback_count: number;
  created_at: string;
  permalink_url: string;
  artwork_url?: string;
  user: {
    username: string;
    avatar_url: string;
  };
}
interface SoundCloudCollectionItem {
  permalink_url?: string;
  url?: string;
  title: string;
  name?: string;
  user?: { username: string; avatar_url: string };
  artist?: string;
  author?: string;
  track_count?: number;
  tracks?: unknown[];
  artwork_url?: string;
  artwork?: string;
  avatar_url?: string;
}
interface SoundCloudCollectionResponse {
  collection?: SoundCloudCollectionItem[];
  results?: SoundCloudCollectionItem[];
}

// JioSaavn API response types
interface JioSaavnImage {
  quality: string;
  url: string;
}
interface JioSaavnSong {
  id: string;
  song?: string;
  name?: string;
  singers?: string;
  primaryArtists?: string;
  duration?: string;
  image?: JioSaavnImage[];
  album?: { id: string; name: string; url: string };
}
interface JioSaavnAlbum {
  id: string;
  title: string;
  artist?: string;
  year?: string;
  image?: JioSaavnImage[];
}
interface JioSaavnArtist {
  id: string;
  title: string;
  description?: string;
  image?: JioSaavnImage[];
}
interface JioSaavnResultSet {
  results?: JioSaavnSong[] | JioSaavnAlbum[] | JioSaavnArtist[] | unknown[];
}
interface JioSaavnSearchData {
  topQuery?: { results?: unknown[] };
  songs?: JioSaavnResultSet;
  albums?: JioSaavnResultSet;
  artists?: JioSaavnResultSet;
}
interface JioSaavnSearchResponse {
  success: boolean;
  data?: JioSaavnSearchData;
}

// ---------- UTILS ----------
const PIPED_INSTANCES = ["https://api.piped.private.coffee"];
const INVIDIOUS_INSTANCES = [
  // "https://api.ytify.workers.dev",
  "https://yt.chocolatemoo53.com",
  "https://inv.thepixora.com",
  "https://yt.omada.cafe",
  "https://invidious.snopyta.org",
  "https://yewtu.be",
  "https://inv.riverside.rocks",
];
const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36";

function scoreThumbnail(
  thumbnail:
    | { width?: number; height?: number; quality?: string; url?: string }
    | undefined
): number {
  if (!thumbnail) return 0;
  const width = thumbnail.width ?? 0;
  const height = thumbnail.height ?? 0;
  if (width > 0 || height > 0) return width * height;

  const quality = thumbnail.quality ?? "";
  const match = quality.match(/(\d+)\s*x\s*(\d+)/i);
  if (!match) return 0;
  return Number(match[1]) * Number(match[2]);
}

function pickBestThumbnailUrl(
  thumbnails:
    | Array<{ width?: number; height?: number; quality?: string; url?: string }>
    | undefined
): string {
  if (!Array.isArray(thumbnails) || thumbnails.length === 0) return "";

  return (
    [...thumbnails].sort((a, b) => scoreThumbnail(b) - scoreThumbnail(a))[0]
      ?.url || ""
  );
}

function upgradeSoundCloudImage(url?: string): string {
  if (!url) return "";

  return url
    .replace("-large.", "-t500x500.")
    .replace("large.jpg", "t500x500.jpg")
    .replace("large.png", "t500x500.png");
}

interface HasItems {
  items?: unknown[];
}

function rewriteAndStandardizeItem(item: any, instanceUrl: string): any {
  if (!item || typeof item !== "object") return item;

  const result = { ...item };

  // For channel items, add a 'name' field (alias for 'author') for frontend compatibility
  if (result.type === "channel" && result.author && !result.name) {
    result.name = result.author;
  }

  // Process videoThumbnails
  if (Array.isArray(result.videoThumbnails)) {
    // Define standard qualities we want to output (in order of preference)
    const qualityMap: Record<
      string,
      { quality: string; width: number; height: number }
    > = {
      maxres: { quality: "maxres", width: 1280, height: 720 },
      maxresdefault: { quality: "maxres", width: 1280, height: 720 },
      sddefault: { quality: "sddefault", width: 640, height: 480 },
      hqdefault: { quality: "high", width: 480, height: 360 },
      mqdefault: { quality: "medium", width: 320, height: 180 },
      default: { quality: "default", width: 120, height: 90 },
    };

    // Map and filter to only standard qualities, rewriting URLs
    const standardized = result.videoThumbnails
      .map((thumb: any) => {
        let qualityKey = thumb.quality || "";
        if (thumb.url.includes("maxres")) qualityKey = "maxres";
        else if (thumb.url.includes("sddefault")) qualityKey = "sddefault";
        else if (thumb.url.includes("hqdefault")) qualityKey = "hqdefault";
        else if (thumb.url.includes("mqdefault")) qualityKey = "mqdefault";
        else if (thumb.url.includes("default")) qualityKey = "default";

        const mapped = qualityMap[qualityKey];
        if (!mapped) return null;

        // Rewrite URL to use the instance domain
        const urlPath = new URL(thumb.url, instanceUrl).pathname;
        return {
          quality: mapped.quality,
          url: `${instanceUrl}${urlPath}`,
          width: mapped.width,
          height: mapped.height,
        };
      })
      .filter(Boolean);

    // Remove duplicates (keep first occurrence of each quality)
    const seen = new Set();
    result.videoThumbnails = standardized.filter((t: any) => {
      if (seen.has(t.quality)) return false;
      seen.add(t.quality);
      return true;
    });
  }

  // Process authorThumbnails
  if (Array.isArray(result.authorThumbnails)) {
    result.authorThumbnails = result.authorThumbnails.map((thumb: any) => {
      // Parse the original URL relative to the instance
      let pathname = new URL(thumb.url, instanceUrl).pathname;

      // If the instance didn't add the /ggpht/ proxy prefix, add it now
      if (!pathname.startsWith("/ggpht/") && pathname.startsWith("/ytc/")) {
        pathname = "/ggpht" + pathname; // → /ggpht/ytc/...
      }

      // Strip the -mo suffix if present (Music channel avatars)
      if (pathname.endsWith("-mo")) {
        pathname = pathname.slice(0, -3);
      }

      return {
        ...thumb,
        url: `${instanceUrl}${pathname}`,
      };
    });
  }

  // Also rewrite any standalone thumbnail URL fields
  if (
    result.playlistThumbnail &&
    typeof result.playlistThumbnail === "string"
  ) {
    const urlPath = new URL(result.playlistThumbnail, instanceUrl).pathname;
    result.playlistThumbnail = `${instanceUrl}${urlPath}`;
  }

  return result;
}

// ---------- PIPED (YouTube) – unchanged ----------
const fetchFromPiped = async (
  endpoint: string
): Promise<Record<string, unknown> | null> => {
  console.log(`[fetchFromPiped] Starting fetch for endpoint: ${endpoint}`);
  for (const baseUrl of PIPED_INSTANCES) {
    try {
      const url = `${baseUrl}${endpoint}`;
      console.log(`[fetchFromPiped] Trying URL: ${url}`);
      const res = await fetch(url, {
        headers: { "User-Agent": USER_AGENT },
      });
      console.log(`[fetchFromPiped] Response status: ${res.status}`);
      if (res.ok) {
        const json: unknown = await res.json();
        console.log(
          `[fetchFromPiped] JSON parsed, keys: ${Object.keys(
            json as object
          ).join(", ")}`
        );
        const itemCount = (json as HasItems).items?.length ?? 0;
        console.log(`[fetchFromPiped] Item count: ${itemCount}`);
        if (json && typeof json === "object")
          return json as Record<string, unknown>;
      } else {
        const text = await res.text();
        console.error(`[fetchFromPiped] Non-OK response body: ${text}`);
      }
    } catch (err) {
      console.error(`[fetchFromPiped] Fetch failed for ${baseUrl}:`, err);
      continue;
    }
  }
  console.error("[fetchFromPiped] All Piped instances failed");
  return null;
};

async function searchYouTube(
  query: string,
  filter: string,
  _page: number,
  _limit: number,
  nextpage?: string
) {
  console.log(
    `[searchYouTube] Query: "${query}", Filter: "${filter}", Nextpage: ${nextpage}`
  );
  const filterParam = filter === "" ? "all" : filter;
  let endpoint = "";
  if (nextpage) {
    endpoint = `/nextpage/search?nextpage=${encodeURIComponent(nextpage)}`;
  } else {
    endpoint = `/search?q=${encodeURIComponent(query)}&filter=${filterParam}`;
  }
  console.log(`[searchYouTube] Piped endpoint: ${endpoint}`);
  const data = await fetchFromPiped(endpoint);
  console.log(
    `[searchYouTube] fetchFromPiped returned: ${data ? "object" : "null"}`
  );

  const rawItems: RawPipedItem[] = (data?.items as RawPipedItem[]) ?? [];
  const newNextpage = data?.nextpage ?? null;
  console.log(`[searchYouTube] Items found: ${rawItems.length}`);

  const results = rawItems.map((item: RawPipedItem) => {
    const videoThumbnails = Array.isArray(item.videoThumbnails)
      ? (item.videoThumbnails as Array<{
          width?: number;
          height?: number;
          quality?: string;
          url?: string;
        }>)
      : undefined;
    const authorThumbnails = Array.isArray(item.authorThumbnails)
      ? (item.authorThumbnails as Array<{
          width?: number;
          height?: number;
          quality?: string;
          url?: string;
        }>)
      : undefined;

    return {
      ...item,
      thumbnailUrl:
        pickBestThumbnailUrl(videoThumbnails) ||
        pickBestThumbnailUrl(authorThumbnails) ||
        (typeof item.playlistThumbnail === "string" ? item.playlistThumbnail : "") ||
        (typeof item.thumbnailUrl === "string" ? item.thumbnailUrl : "") ||
        (typeof item.thumbnail === "string" ? item.thumbnail : ""),
      source: "youtube" as const,
    };
  });

  console.log(`[searchYouTube] Final results count: ${results.length}`);
  return { items: results, nextpage: newNextpage };
}

// ---------- INVIDIOUS (YouTube) – NEW, exactly like Piped ----------
function mapFilterToInvidiousType(filter: string): string | undefined {
  const lower = filter.toLowerCase();
  if (lower === "video" || lower === "videos") return "video";
  if (lower === "playlist" || lower === "playlists") return "playlist";
  if (lower === "channel" || lower === "channels") return "channel";
  return undefined;
}

async function searchInvidious(
  query: string,
  filter: string,
  page: number,
  limit: number
) {
  console.log(
    `[searchInvidious] Query: "${query}", Filter: "${filter}", Page: ${page}, Limit: ${limit}`
  );
  const effectiveLimit = Math.min(limit, 20);
  const typeParam = mapFilterToInvidiousType(filter);

  const instances = [
    "https://yt.chocolatemoo53.com",
    "https://inv.thepixora.com",
    "https://yt.omada.cafe",
    "https://invidious.snopyta.org",
    "https://yewtu.be",
    "https://inv.riverside.rocks",
  ];

  for (const instance of instances) {
    try {
      const url = new URL(`${instance}/api/v1/search`);
      url.searchParams.set("q", query);
      url.searchParams.set("page", String(page));
      if (typeParam) url.searchParams.set("type", typeParam);

      console.log(`[searchInvidious] Trying ${url.toString()}`);
      const res = await fetch(url.toString(), {
        headers: { "User-Agent": USER_AGENT },
      });
      console.log(
        `[searchInvidious] Response status: ${res.status} from ${instance}`
      );

      if (res.ok) {
        let data = (await res.json()) as InvidiousSearchItem[];
        if (!Array.isArray(data)) continue;

        // Standardize: fix thumbnail URLs and qualities
        const standardized = data.map((item) =>
          rewriteAndStandardizeItem(item, instance)
        );

        // Normalize each item: extract a direct thumbnailUrl and set source to "youtube"
        const items = standardized.slice(0, effectiveLimit).map((item) => {
          let thumbnailUrl = "";

          // Extract best thumbnail for videos
          if (item.type === "video" && Array.isArray(item.videoThumbnails)) {
            // Prefer highest quality (maxres > sddefault > hqdefault etc.)
            const sorted = [...item.videoThumbnails].sort(
              (a, b) => b.width - a.width
            );
            thumbnailUrl = sorted[0]?.url || "";
          }
          // Playlist thumbnail
          else if (item.type === "playlist" && item.playlistThumbnail) {
            thumbnailUrl = item.playlistThumbnail;
          }
          // Channel avatar
          else if (
            item.type === "channel" &&
            Array.isArray(item.authorThumbnails)
          ) {
            thumbnailUrl = item.authorThumbnails[0]?.url || "";
          }

          // Return a clean object that matches the frontend's expectations
          return {
            ...item,
            thumbnailUrl,
            source: "youtube", // Forces 128×72 / 48×48 layout in ResultItem
          };
        });

        const hasMore = data.length >= effectiveLimit;
        const nextpage = hasMore ? String(page + 1) : null;
        console.log(
          `[searchInvidious] Success from ${instance}: ${items.length} items (normalized with thumbnailUrl)`
        );
        return { items, nextpage };
      } else {
        const text = await res.text();
        console.error(`[searchInvidious] Failed ${instance}: ${res.status}`);
      }
    } catch (err) {
      console.error(`[searchInvidious] Error with ${instance}:`, err);
    }
  }
  return { items: [], nextpage: null };
}

// ---------- YouTube Music (Piped) – unchanged ----------
function musicFilterMap(filter: string): string {
  const map: Record<string, string> = {
    songs: "music_songs",
    videos: "music_videos",
    albums: "music_albums",
    playlists: "music_playlists",
    channels: "music_artists",
    "": "music_songs",
  };
  return map[filter] || filter;
}

async function searchYouTubeMusic(
  query: string,
  filter: string,
  page: number,
  limit: number,
  nextpage?: string
) {
  console.log(`[searchYouTubeMusic] Query: "${query}", Filter: "${filter}"`);
  const musicFilter = musicFilterMap(filter || "songs");
  const result = await searchYouTube(query, musicFilter, page, limit, nextpage);
  return {
    items: result.items.map((item) => ({
      ...(item as Record<string, unknown>),
      source: "youtubemusic" as const,
    })),
    nextpage: result.nextpage ?? null,
  };
}

// ---------- SoundCloud – unchanged ----------
async function searchSoundCloud(
  query: string,
  filter: string,
  page: number,
  limit: number
) {
  console.log(
    `[searchSoundCloud] Query: "${query}", Filter: "${filter}", Page: ${page}, Limit: ${limit}`
  );
  const f = (filter || "").toLowerCase();
  const offset = (page - 1) * limit;

  if (f === "playlists" || f === "albums") {
    const scType = f === "playlists" ? "playlists" : "albums";
    const url = `https://proxy.searchsoundcloud.com/${scType}?q=${encodeURIComponent(
      query
    )}&limit=${limit}&offset=${offset}`;
    console.log(`[searchSoundCloud] Fetching: ${url}`);
    const res = await fetch(url, {
      headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    });
    console.log(`[searchSoundCloud] Response status: ${res.status}`);
    if (!res.ok) {
      const text = await res.text();
      console.error(`[searchSoundCloud] Non-OK body: ${text}`);
      return { items: [], nextpage: null };
    }
    const json: unknown = await res.json();
    const data = json as SoundCloudCollectionResponse;
    const collection = data?.collection ?? data?.results ?? [];
    console.log(`[searchSoundCloud] Collection size: ${collection.length}`);
    const items = collection.map((c) => ({
      id: c.permalink_url || c.url || "",
      title: c.title || c.name || "",
      author: c.user?.username || c.artist || c.author || "",
      videoCount:
        c.track_count ??
        (Array.isArray(c.tracks) ? c.tracks.length : undefined),
      thumbnailUrl: upgradeSoundCloudImage(
        c.artwork_url || c.artwork || c.user?.avatar_url || ""
      ),
      type: scType === "playlists" ? "playlist" : "album",
      source: "soundcloud",
    }));
    return { items, nextpage: null };
  } else {
    const url = `https://proxy.searchsoundcloud.com/tracks?q=${encodeURIComponent(
      query
    )}&limit=${limit}&offset=${offset}`;
    console.log(`[searchSoundCloud] Fetching tracks: ${url}`);
    const res = await fetch(url, {
      headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    });
    console.log(`[searchSoundCloud] Response status: ${res.status}`);
    if (!res.ok) {
      const text = await res.text();
      console.error(`[searchSoundCloud] Non-OK body: ${text}`);
      return { items: [], nextpage: null };
    }
    const json: unknown = await res.json();
    const data = json as SoundCloudTrackResponse;
    const tracks = data?.collection ?? [];
    console.log(`[searchSoundCloud] Tracks size: ${tracks.length}`);
    const items = tracks
      .filter((t) => t.kind === "track" && t.duration >= 10000)
      .map((t) => ({
        id: String(t.id),
        title: t.title,
        author: t.user?.username,
        duration: String(Math.floor(t.duration / 1000)),
        views: String(t.playback_count || 0),
        uploaded: "",
        thumbnailUrl: upgradeSoundCloudImage(
          t.artwork_url || t.user?.avatar_url
        ),
        type: "song",
        source: "soundcloud",
      }));
    return { items, nextpage: null };
  }
}

// ---------- JioSaavn – unchanged ----------
async function searchJioSaavn(query: string) {
  console.log(`[searchJioSaavn] Query: "${query}"`);
  try {
    const url = `https://streamifyjiosaavn.vercel.app/api/search?query=${encodeURIComponent(
      query
    )}`;
    console.log(`[searchJioSaavn] Fetching: ${url}`);
    const res = await fetch(url, {
      headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    });
    console.log(`[searchJioSaavn] Response status: ${res.status}`);
    if (!res.ok) {
      const text = await res.text();
      console.error(`[searchJioSaavn] Non-OK body: ${text}`);
      return { items: [], nextpage: null };
    }
    const json: unknown = await res.json();
    const data = json as JioSaavnSearchResponse;

    if (!data || !data.success) {
      console.log("[searchJioSaavn] Not successful");
      return { items: [], nextpage: null };
    }

    const topQuery: unknown[] =
      (data.data?.topQuery?.results as unknown[]) ?? [];
    const songs: JioSaavnSong[] =
      (data.data?.songs?.results as JioSaavnSong[]) ?? [];
    const albums: JioSaavnAlbum[] =
      (data.data?.albums?.results as JioSaavnAlbum[]) ?? [];
    const artists: JioSaavnArtist[] =
      (data.data?.artists?.results as JioSaavnArtist[]) ?? [];

    console.log(
      `[searchJioSaavn] TopQuery: ${topQuery.length}, Songs: ${songs.length}, Albums: ${albums.length}, Artists: ${artists.length}`
    );

    const results: object[] = [];

    for (const item of topQuery) {
      const obj = item as {
        id?: string;
        title?: string;
        description?: string;
        image?: JioSaavnImage[];
      };
      const thumb =
        obj.image?.find((img) => img.quality === "500x500")?.url ||
        obj.image?.[0]?.url;
      results.push({
        id: String(obj.id),
        title: obj.title || "",
        author: obj.description || "",
        thumbnailUrl: thumb,
        type: "unknown",
        source: "jiosaavn",
      });
    }

    for (const s of songs) {
      const thumb =
        s.image?.find((img) => img.quality === "500x500")?.url ||
        s.image?.[0]?.url;
      results.push({
        id: String(s.id),
        title: s.song || s.name || "",
        author: s.singers || s.primaryArtists || "",
        duration: s.duration ? String(s.duration) : "0",
        thumbnailUrl: thumb,
        type: "song",
        source: "jiosaavn",
        albumId: s.album?.id,
        albumName: s.album?.name,
      });
    }

    for (const alb of albums) {
      const thumb =
        alb.image?.find((img) => img.quality === "500x500")?.url ||
        alb.image?.[0]?.url;
      results.push({
        id: String(alb.id),
        title: alb.title,
        author: alb.artist || "",
        thumbnailUrl: thumb,
        type: "album",
        source: "jiosaavn",
        albumYear: alb.year,
      });
    }

    for (const art of artists) {
      const thumb =
        art.image?.find((img) => img.quality === "500x500")?.url ||
        art.image?.[0]?.url;
      results.push({
        id: String(art.id),
        title: art.title,
        author: art.description || "",
        thumbnailUrl: thumb,
        type: "artist",
        source: "jiosaavn",
      });
    }

    console.log(`[searchJioSaavn] Final results: ${results.length}`);
    return { items: results, nextpage: null };
  } catch (err) {
    console.error("[searchJioSaavn] Error:", err);
    return { items: [], nextpage: null };
  }
}

// ---------- MAIN ROUTE ----------
app.get("/search", async (req, res) => {
  console.log("=========================================");
  console.log(
    "[EXPRESS /search] Request received at",
    new Date().toISOString()
  );
  console.log("[EXPRESS /search] Full URL:", req.originalUrl);
  console.log("[EXPRESS /search] Query params:", req.query);

  const { q, source, filter, page, limit, nextpage } = req.query;

  if (!q || typeof q !== "string") {
    console.log("[EXPRESS /search] No valid query, returning 400");
    return res.status(400).json({ items: [] });
  }

  const sourceParam = (source as string) || "youtube";
  const filterParam = (filter as string) || "";
  const pageNum = parseInt(page as string) || 1;
  const limitNum = parseInt(limit as string) || 20;
  const nextpageToken = (nextpage as string) || undefined;

  console.log(
    `[EXPRESS /search] Parsed: source=${sourceParam}, filter=${filterParam}, page=${pageNum}, limit=${limitNum}, nextpage=${nextpageToken}`
  );

  try {
    let result: { items: unknown[]; nextpage?: unknown } = {
      items: [],
      nextpage: null,
    };

    switch (sourceParam) {
      case "piped": // original Piped method, preserved
        console.log("[EXPRESS /search] Calling searchYouTube (Piped)...");
        result = await searchYouTube(
          q,
          filterParam,
          pageNum,
          limitNum,
          nextpageToken
        );
        break;
      case "youtube": // now uses Invidious
      case "invidious":
        console.log("[EXPRESS /search] Calling searchInvidious...");
        result = await searchInvidious(q, filterParam, pageNum, limitNum);
        break;
      case "youtubemusic":
        console.log("[EXPRESS /search] Calling searchYouTubeMusic...");
        result = await searchYouTubeMusic(
          q,
          filterParam,
          pageNum,
          limitNum,
          nextpageToken
        );
        break;
      case "soundcloud":
        console.log("[EXPRESS /search] Calling searchSoundCloud...");
        result = await searchSoundCloud(q, filterParam, pageNum, limitNum);
        break;
      case "jiosaavn":
        console.log("[EXPRESS /search] Calling searchJioSaavn...");
        result = await searchJioSaavn(q);
        break;
      default:
        console.log("[EXPRESS /search] Unknown source, returning empty");
        result = { items: [] };
    }

    console.log(
      `[EXPRESS /search] Returning ${
        result.items.length
      } items, nextpage: ${JSON.stringify(result.nextpage)}`
    );
    return res.json({ items: result.items, nextpage: result.nextpage ?? null });
  } catch (error) {
    console.error("[EXPRESS /search] Caught error:", error);
    return res.status(500).json({ items: [], error: "Search failed" });
  }
});

app.listen(PORT, () =>
  console.log(`✅ Express server running on http://localhost:${PORT}`)
);
